In [1]:
import pandas as pd

# Data Loading

In [2]:
questions = pd.read_csv('../data/raw/questions_clean.csv')

In [3]:
data = pd.read_csv('../data/raw/websites_updated.csv')

# Mini sample for test

In [30]:
questions.sample(200).to_csv('../data/raw/questions_clean_sample_200.csv')

In [33]:
data.sample(200).to_csv('../data/raw/websites_updated_sample_200.csv')

# EDA

In [43]:
data.head(3)

,web_id,url,kind,title,text
0,1,https://alfabank.ru/,html,"Альфа-Банк - кредитные и дебетовые карты, кредиты наличными, автокредитование, ипотека и другие банковские услуги физическим и юридическим лицам – Альфа-Банк","Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке"
1,2,https://alfabank.ru/a-club/,html,А-Клуб. Деньги имеют значение,"Брокерские услуги\nОткрытие брокерского счёта в приложении Альфа‑Инвестиции. Расширенный инструментарий: биржевая, внебиржевая и маржинальная торговля, биржевые структурные облигации, первичные размещения\nИнвестиционное консультирование\nДля инвесторов с брокерским счётом в Альфа‑Инвестициях — привлекательные условия и автоматизированная консультационная платформа\nАльтернативные инвестиции\nИнвестирование в фонды недвижимости, private equity и венчурные фонды, капитал быстрорастущих компаний\nСтраховые и пенсионные программы\nИнвестиционное и накопительное страхование жизни. Дополнительные юридические и налоговые преимущества. Структурирование передачи капитала\nАльфа‑Капитал\nИндивидуальные или готовые стратегии, открытые ПИФы и БПИФы — для простого и эффективного доступа на рынок, ЗПИФы — для структурирования капитала и реализации индивидуальных стратегий управления благосостоянием\nИндивидуальные решения\nСтруктурирование активов в РФ и за рубежом, создание сложных финансовых продуктов по запросу\nДепозиты и накопительные счета\nВозможность установления индивидуальных тарифов\nБанковские карты\nВозможность привязать карты к счетам в 23 валютах; карты с привилегиями и кэшбэком до 15%\nДрагоценные металлы и камни\nМерные и стандартные слитки золота, бриллианты инвестиционного качества\nСделки через аккредитив или депозитарий\nБезопасность и гарантия сделок любой сложности\nБиометрический депозитарий\nУсиленное круглосуточное хранилище\nКредитование\nИпотека по паспорту на срок до 30 лет на строящееся и готовое жильё, включая рефинансирование\nПлатёжные аксессуары\nКерамические платёжные кольца с бесконтакной оплатой\nПеревозка, доставка и инкассация наличных\nСвоя служба инкассации\nЛучший сервис Private Banking\nПо версии Frank RG\nЛучший российский банк для состоятельных клиентов\nПо версии Wealth Navigator\nЛучший Private Banking в 13 номинациях\nПо версии Euromoney\nЧастые вопросы\nКакая минимальная и максимальная сумма пополнения брокерского счёта для клиентов в возрасте от 14 до 18 лет?\nХотите получить больше информации?\nСвяжитесь с нами, и мы ответим на все вопросы\n+7 495 777 32 55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"
2,3,https://alfabank.ru/a-club/ultimate/,html,А-Клуб. Деньги имеют значение,"Хотите получить больше информации?\nПозвоните нам и мы ответим на все вопросы\n+7 495 777-32-55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"

In [44]:
questions.head()

   q_id                                                     query
0     1                                               Номер счета
1     2                                     Где узнать бик и счёт
2     3    Мне не приходят коды для подтверждения данной операции
3     4      Оформила рассрочку ,но уведомлений никаких не пришло
4     5  Здравствуйте, когда смогу пользоваться кредитной картой?

In [9]:
data.kind.value_counts()

kind
html        1802
document     135
Name: count, dtype: int64

In [ ]:
data[data.kind=='document'].head(3)

In [18]:
data.text.iloc[0]

'Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке'

# Extracting importance columns

In [47]:
data_clean = data[['web_id', 'title', 'text']]

In [49]:
data_clean.head(3)

,web_id,title,text
0,1,"Альфа-Банк - кредитные и дебетовые карты, кредиты наличными, автокредитование, ипотека и другие банковские услуги физическим и юридическим лицам – Альфа-Банк","Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке"
1,2,А-Клуб. Деньги имеют значение,"Брокерские услуги\nОткрытие брокерского счёта в приложении Альфа‑Инвестиции. Расширенный инструментарий: биржевая, внебиржевая и маржинальная торговля, биржевые структурные облигации, первичные размещения\nИнвестиционное консультирование\nДля инвесторов с брокерским счётом в Альфа‑Инвестициях — привлекательные условия и автоматизированная консультационная платформа\nАльтернативные инвестиции\nИнвестирование в фонды недвижимости, private equity и венчурные фонды, капитал быстрорастущих компаний\nСтраховые и пенсионные программы\nИнвестиционное и накопительное страхование жизни. Дополнительные юридические и налоговые преимущества. Структурирование передачи капитала\nАльфа‑Капитал\nИндивидуальные или готовые стратегии, открытые ПИФы и БПИФы — для простого и эффективного доступа на рынок, ЗПИФы — для структурирования капитала и реализации индивидуальных стратегий управления благосостоянием\nИндивидуальные решения\nСтруктурирование активов в РФ и за рубежом, создание сложных финансовых продуктов по запросу\nДепозиты и накопительные счета\nВозможность установления индивидуальных тарифов\nБанковские карты\nВозможность привязать карты к счетам в 23 валютах; карты с привилегиями и кэшбэком до 15%\nДрагоценные металлы и камни\nМерные и стандартные слитки золота, бриллианты инвестиционного качества\nСделки через аккредитив или депозитарий\nБезопасность и гарантия сделок любой сложности\nБиометрический депозитарий\nУсиленное круглосуточное хранилище\nКредитование\nИпотека по паспорту на срок до 30 лет на строящееся и готовое жильё, включая рефинансирование\nПлатёжные аксессуары\nКерамические платёжные кольца с бесконтакной оплатой\nПеревозка, доставка и инкассация наличных\nСвоя служба инкассации\nЛучший сервис Private Banking\nПо версии Frank RG\nЛучший российский банк для состоятельных клиентов\nПо версии Wealth Navigator\nЛучший Private Banking в 13 номинациях\nПо версии Euromoney\nЧастые вопросы\nКакая минимальная и максимальная сумма пополнения брокерского счёта для клиентов в возрасте от 14 до 18 лет?\nХотите получить больше информации?\nСвяжитесь с нами, и мы ответим на все вопросы\n+7 495 777 32 55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"
2,3,А-Клуб. Деньги имеют значение,"Хотите получить больше информации?\nПозвоните нам и мы ответим на все вопросы\n+7 495 777-32-55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"

# Answer checking

In [6]:
pd.set_option('display.max_colwidth', None)

In [61]:
ans.values

array([[1136, 1, 1192, '1192_0',
        'Как войти в Альфа-Онлайн\nГде найти номер карты или счёта\nЧто делать, если я не помню логин и пароль\nКак создать иконку Альфа-Онлайн\nЕсли не получается войти в Альфа-Онлайн, позвоните в поддержку: 8 80',
        0.6250022053718567],
       [1136, 2, 1904, '1904_0',
        'Как активировать карту?\nВ мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код.',
        0.5892703533172607],
       [1136, 3, 1523, '1523_0',
        'Общая информация Мобильное приложение и Альфа-Онлайн Комиссии по карте Перевыпуск, блокировка и закрытие Как перестать пользоваться картой? Как пользоваться картой? Начало использования Всё про кэшбэк',
        0.5331138968467712],
       ...,
       [2481, 3, 1607, '1607_0',
        'Лента операций\nКак устроен интернет-банк\nГде посмотреть все мои счета?\nЕсть 2 способа посмотреть все счета:\nНа главной странице интернет-банка в блоке Счета на главной нажмите на кнопку Все счета.\nВ л',
        0.5648996829986572],
       [2481, 4, 480, '480_0',
        'Архив тарифов на комплексное банковское обслуживание',
        0.5639533996582031],
       [2481, 5, 1903, '1903_0',
        'В каких банках смогу снять наличные?\nОплачивать покупки и снимать наличные сможете в этих:\n\n• В Армении — во всех банках-участниках платёжной системы ArCa.\n• В Таджикистане — во всех банках-участниках',
        0.5472157001495361]], shape=(1000, 6), dtype=object)

In [60]:
ans.head(10)

,q_id,rank,web_id,chunk_id,chunk_text,score
0,1136,1,1192,1192_0,"Как войти в Альфа-Онлайн\nГде найти номер карты или счёта\nЧто делать, если я не помню логин и пароль\nКак создать иконку Альфа-Онлайн\nЕсли не получается войти в Альфа-Онлайн, позвоните в поддержку: 8 80",0.625002
1,1136,2,1904,1904_0,Как активировать карту?\nВ мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код.,0.589270
2,1136,3,1523,1523_0,"Общая информация Мобильное приложение и Альфа-Онлайн Комиссии по карте Перевыпуск, блокировка и закрытие Как перестать пользоваться картой? Как пользоваться картой? Начало использования Всё про кэшбэк",0.533114
3,1136,4,1589,1589_0,Как пользоваться картой\nКак перестать пользоваться картой?\nПомощь\nДебетовые карты\nКак активировать карту?\nВ мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код.\nК,0.524637
4,1136,5,44,44_0,"Выберите приложение, операционную систему и пользуйтесь",0.516911
5,2185,1,890,890_1,"и зарегистрировал её заново. Но в приложении не отображаются покупки, оплаченные через Mir Pay. Почему? Я расплатился пластиковой картой в магазине, но не вижу покупку в приложении Mir Pay. Почему? Ка",0.626835
6,2185,2,1921,1921_6,"браузере на символ замка, который появляется при посещении сайтов, разрешающих безопасную передачу данных. Он должен быть выдан первоначальному владельцу веб-сайта. Мошенники списали деньги с карты: ч",0.618829
7,2185,3,1358,1358_0,08.08.2013\nС 1 августа 2013 года Альфа-Банк изменил процентные ставки по кредитным картам.,0.598648
8,2185,4,1887,1887_0,"Тарифы и комиссии\nПереводы c карты на карту\nКэшбэк\nНачало использования\nОбщая информация по карте\nВыпуск карты\nЕсли карта Альфа-Бизнес с кэшбэком была перевыпущена, кэшбэк подключается автоматически?\n",0.596366
9,2185,5,1249,1249_0,Подтвердите запрос пополнения вашего счёта из другого банка\nПродолжить в Альфа-Онлайн,0.593668

In [87]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [88]:
for j, i in enumerate(ans.values):
    if True:
        print('------НАЧАЛО-------')
        print('Question:')
        print(f'" { questions[questions.q_id == i[0]]['query']} "')
        print('Title of doc:')
        print(f'"{data[data.web_id == i[2]]['title']}"')
        print('Chunk from doc:')
        print(f'"{i[4]}"')
        #print(data[data.web_idк == i[1]]['text'])
        print(f'score : {i[5]}')
        print('-------КОНЕЦ--------')
        print()
        #break

------НАЧАЛО-------
Question:
" 1135    Как скачать альфу на айфоне
Name: query, dtype: object "
Title of doc:
"1191    Альфа-Онлайн. Ответа на вопросы.
Name: title, dtype: object"
Chunk from doc:
"Как войти в Альфа-Онлайн Где найти номер карты или счёта Что делать, если я не помню логин и пароль Как создать иконку Альфа-Онлайн Если не получается войти в Альфа-Онлайн, позвоните в поддержку: 8 80"
score : 0.3271783067736012
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1135    Как скачать альфу на айфоне
Name: query, dtype: object "
Title of doc:
"1903    Как активировать карту?
Name: title, dtype: object"
Chunk from doc:
"Как активировать карту? В мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код."
score : 0.3103137024515535
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1135    Как скачать альфу на айфоне
Name: query, dtype: object "
Title of doc:
"1609    Лучшее банковское приложение на андроид
Name: title, dtype: object"
Chunk from doc:
"40 секунд — и готово 📲 Скачивайте приложение только с сайта alfabank.ru. Или из магазина приложений для Android — RuStore При установке появится сообщение о ненадёжном источнике — это стандартное пред"
score : 0.3010030436126202
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1135    Как скачать альфу на айфоне
Name: query, dtype: object "
Title of doc:
"1520    Как установить мобильное приложение?
Name: title, dtype: object"
Chunk from doc:
"Общая информация Мобильное приложение и Альфа-Онлайн Комиссии по карте Перевыпуск, блокировка и закрытие Как перестать пользоваться картой? Как пользоваться картой? Начало использования Всё про кэшбэк"
score : 0.2952092055565068
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1135    Как скачать альфу на айфоне
Name: query, dtype: object "
Title of doc:
"1522    Как пользоваться Альфа-Онлайн?
Name: title, dtype: object"
Chunk from doc:
"Общая информация Мобильное приложение и Альфа-Онлайн Комиссии по карте Перевыпуск, блокировка и закрытие Как перестать пользоваться картой? Как пользоваться картой? Начало использования Всё про кэшбэк"
score : 0.2875494731289657
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2184    Пропала кредитная карта из моего приложения
Name: query, dtype: object "
Title of doc:
"889    Mir Pay — просто и удобно – Привязать карту МИР к телефону – Альфа-Банк
Name: title, dtype: object"
Chunk from doc:
"Я удалил карту и зарегистрировал её заново. Но в приложении не отображаются покупки, оплаченные через Mir Pay. Почему? Я расплатился пластиковой картой в магазине, но не вижу покупку в приложении Mir "
score : 0.3304033138082091
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2184    Пропала кредитная карта из моего приложения
Name: query, dtype: object "
Title of doc:
"865    Бесконтактные пластиковые карты — заказать бесконтактную nfc карту в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"Дебетовая карта Альфа-Банка и билайн Бесплатно выпуск и обслуживание 25% кэшбэк за оплату связи и услуг билайн Без комиссии все переводы и платежи Сегодня даже школьнику известно, как пользоваться бес"
score : 0.3248116387210872
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2184    Пропала кредитная карта из моего приложения
Name: query, dtype: object "
Title of doc:
"1248    Без названия
Name: title, dtype: object"
Chunk from doc:
"Подтвердите запрос пополнения вашего счёта из другого банка Продолжить в Альфа-Онлайн"
score : 0.309740229157903
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2184    Пропала кредитная карта из моего приложения
Name: query, dtype: object "
Title of doc:
"1886    Если карта Альфа-Бизнес с кэшбэком была перевыпущена, кэшбэк подключается автоматически?
Name: title, dtype: object"
Chunk from doc:
"Тарифы и комиссии Переводы c карты на карту Кэшбэк Начало использования Общая информация по карте Выпуск карты Если карта Альфа-Бизнес с кэшбэком была перевыпущена, кэшбэк подключается автоматически? "
score : 0.3079598491964974
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2184    Пропала кредитная карта из моего приложения
Name: query, dtype: object "
Title of doc:
"111    Mir Pay — просто и удобно – Привязать карту МИР к телефону – Альфа-Банк
Name: title, dtype: object"
Chunk from doc:
"В каких странах можно расплатиться с Mir Pay? Как узнать реквизиты цифровой карты Мир? Что такое «Карта по умолчанию»? Как расплатиться картой, если она не назначена «Картой по умолчанию»? Как удалить"
score : 0.3050008346953028
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6460    я не мгу нати раздел витрина
Name: query, dtype: object "
Title of doc:
"1741    База знаний торгового эквайринга
Name: title, dtype: object"
Chunk from doc:
"про про про про про База знаний торгового эквайринга"
score : 0.2656661570072174
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6460    я не мгу нати раздел витрина
Name: query, dtype: object "
Title of doc:
"647    7000 бонусов на продвижение — Программа лояльности 🅰️ Альфа‑Банка
Name: title, dtype: object"
Chunk from doc:
"Широкий ассортимент Электронные книги на разных языках Мобильный доступ 25 приложений для чтения Бесплатный фрагмент До 25% книги для ознакомления Сервис Круглосуточная поддержка"
score : 0.2543753981590271
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6460    я не мгу нати раздел витрина
Name: query, dtype: object "
Title of doc:
"1581    Политика в отношении обработки персональных данных в Альфа-Банке — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Спецсчета Банковское обслуживание Инкассация Платежи в рублях Быстрые платежи Управление ликвидностью Коды самоинкассации Банковское сопровождение контрактов Цифровой банк Интернет-банк Мобильное прил"
score : 0.2502184510231018
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6460    я не мгу нати раздел витрина
Name: query, dtype: object "
Title of doc:
"1379    Альфа-Банк изменил ставки по накопительным счетам для физических лиц
Name: title, dtype: object"
Chunk from doc:
"Спецсчета Банковское обслуживание Инкассация Платежи в рублях Быстрые платежи Управление ликвидностью Коды самоинкассации Банковское сопровождение контрактов Цифровой банк Интернет-банк Мобильное прил"
score : 0.2502184510231018
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6460    я не мгу нати раздел витрина
Name: query, dtype: object "
Title of doc:
"425    Альфа-Банк: страница не найдена
Name: title, dtype: object"
Chunk from doc:
"Спецсчета Банковское обслуживание Инкассация Платежи в рублях Быстрые платежи Управление ликвидностью Коды самоинкассации Банковское сопровождение контрактов Цифровой банк Интернет-банк Мобильное прил"
score : 0.2502184510231018
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2489    Подключена
Name: query, dtype: object "
Title of doc:
"1771    YandexPlus_CC.pdf
Name: title, dtype: object"
Chunk from doc:
"Действует с 01.09.20"
score : 0.2638668715953827
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2489    Подключена
Name: query, dtype: object "
Title of doc:
"110    Удаленные каналы обслуживания Альфа-Банка — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Удаленные каналы обслуживания Альфа-Банка"
score : 0.2407296150922775
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2489    Подключена
Name: query, dtype: object "
Title of doc:
"15    Без названия
Name: title, dtype: object"
Chunk from doc:
"Введите номер телефона Телефон Телефон Продолжить"
score : 0.2328331172466278
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2489    Подключена
Name: query, dtype: object "
Title of doc:
"1903    Как активировать карту?
Name: title, dtype: object"
Chunk from doc:
"Как активировать карту? В мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код."
score : 0.2226256430149078
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2489    Подключена
Name: query, dtype: object "
Title of doc:
"467    Пресс-служба Альфа-Банка
Name: title, dtype: object"
Chunk from doc:
"Пресс-служба Альфа-Банка"
score : 0.2205300033092498
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4382    Где мой кэшбека за заправку на тебойл
Name: query, dtype: object "
Title of doc:
"402    Проценты на остаток брокерского счёта
Name: title, dtype: object"
Chunk from doc:
"Проценты на остаток брокерского счёта"
score : 0.2789828887198663
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4382    Где мой кэшбека за заправку на тебойл
Name: query, dtype: object "
Title of doc:
"748    Открыть ИП онлайн в 🅰️ Альфа‑Банке — 🔸 Быстрая регистрация и удаленная подача заявления в налоговую — 🔸 Открытие ИП за 0 ₽
Name: title, dtype: object"
Chunk from doc:
"Бесплатно Платежи 24/7 Внутри Альфа‑Банка Кэшбэк до 10% За бизнес-расходы До 100%"
score : 0.2789301772240329
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4382    Где мой кэшбека за заправку на тебойл
Name: query, dtype: object "
Title of doc:
"65    Предложение для юридических лиц  ООО «Система телеком Активы»
Name: title, dtype: object"
Chunk from doc:
"Специальные условия по РКО Проценты на остатки по счетам Электронная банковская гарантия всего за 1 день Экспресс‑лизинг для покупки транспорта, техники, оборудования Покрытые аккредитивы в рублях для"
score : 0.2709448573931791
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4382    Где мой кэшбека за заправку на тебойл
Name: query, dtype: object "
Title of doc:
"112    Моментальный выпуск карт из приложения – Заказать банковскую карту через мобильное приложение Альфа-Банка
Name: title, dtype: object"
Chunk from doc:
"карту? Как быстро появится новая карта в приложении «Альфа-Мобайл»? Как быстро появится предодобренная кредитная карта? На каких устройствах я могу заказать и моментально получить карту? Где я могу ра"
score : 0.2672762943051209
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4382    Где мой кэшбека за заправку на тебойл
Name: query, dtype: object "
Title of doc:
"1884    Как будет списана комиссия за обслуживания карты, если я закрываю счет?
Name: title, dtype: object"
Chunk from doc:
"Тарифы и комиссии Переводы c карты на карту Кэшбэк Начало использования Общая информация по карте Выпуск карты Как будет списана комиссия за обслуживания карты, если я закрываю счет? При закрытии счет"
score : 0.2653253382444597
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1859    Смс стали приходить!
Name: query, dtype: object "
Title of doc:
"1196    Больше лимит - больше возможностей
Name: title, dtype: object"
Chunk from doc:
"Прислали смс, пуш и электронное письмо с информацией — сколько нужно потратить, чтобы получить кэшбэк 10% Максимальная сумма вознаграждения в рамках акции Призовой фонд акции ограничен — успейте первы"
score : 0.2595841674984419
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1859    Смс стали приходить!
Name: query, dtype: object "
Title of doc:
"1306    С 5 августа обновляем акцию «300 ГБ за перенос номера»
Name: title, dtype: object"
Chunk from doc:
"В марте 2025 года Альфа‑Банк запустил мобильную связь Альфа‑Мобайл и предложил новым абонентам участвовать в акции. Все клиенты банка могли оформить сим-карту с тарифом Лайк, перейти со своим прежним "
score : 0.2556630373001098
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1859    Смс стали приходить!
Name: query, dtype: object "
Title of doc:
"463    Изменились условия акции Альфа‑Мобайл со скидкой 100% на тариф Лайк
Name: title, dtype: object"
Chunk from doc:
"С 5 августа новые абоненты, которые впервые подключат тариф Лайк, получат 16 дней бесплатного обслуживания вместо 30. Подробнее об условиях акции со скидкой 100% мы уже рассказывали в новостях. В тари"
score : 0.2249190260829852
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1859    Смс стали приходить!
Name: query, dtype: object "
Title of doc:
"15    Без названия
Name: title, dtype: object"
Chunk from doc:
"Введите номер телефона Телефон Телефон Продолжить"
score : 0.2185865640640258
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1859    Смс стали приходить!
Name: query, dtype: object "
Title of doc:
"859    Лучшее мобильное приложение
Name: title, dtype: object"
Chunk from doc:
"Приложение Альфа-Банк в вашем смартфоне Отсканируйте QR-код камерой смартфона, перейдите по ссылке и следуйте инструкции."
score : 0.2180176079273224
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6587    Вы можете прочитать сообщения выше?
Name: query, dtype: object "
Title of doc:
"1203    Без названия
Name: title, dtype: object"
Chunk from doc:
"Мы бы хотели сделать наши рассылки полезнее. Пройдите простой опрос и помогите нам."
score : 0.3020759224891662
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6587    Вы можете прочитать сообщения выше?
Name: query, dtype: object "
Title of doc:
"15    Без названия
Name: title, dtype: object"
Chunk from doc:
"Введите номер телефона Телефон Телефон Продолжить"
score : 0.2620958089828491
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6587    Вы можете прочитать сообщения выше?
Name: query, dtype: object "
Title of doc:
"1313    Пресс-служба Альфа-банка
Name: title, dtype: object"
Chunk from doc:
"Пресс-служба Альфа-Банка Если вы хотите связаться с PR или оставить запрос — пишите на press@alfabank.ru Пресс-релизы Альфа-Банка: alfabank.ru/news/"
score : 0.2615123460858665
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6587    Вы можете прочитать сообщения выше?
Name: query, dtype: object "
Title of doc:
"1248    Без названия
Name: title, dtype: object"
Chunk from doc:
"Подтвердите запрос пополнения вашего счёта из другого банка Продолжить в Альфа-Онлайн"
score : 0.2590081393718719
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6587    Вы можете прочитать сообщения выше?
Name: query, dtype: object "
Title of doc:
"1605    Как войти в Альфа-Кредит по УКЭП?
Name: title, dtype: object"
Chunk from doc:
"Общие сведения Как войти в Альфа-Кредит по УКЭП? Если у вас есть сертификат УКЭП и вы уже использовали его в Альфа-Кредите, тогда выберите этот вариант для входа в систему. Нажмите Показать другие сер"
score : 0.2578581785685761
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1569    заказать справку о реквизиты счета
Name: query, dtype: object "
Title of doc:
"1612    Как получить справку или выписку по дебетовой карте?
Name: title, dtype: object"
Chunk from doc:
"Как получить справку или выписку по дебетовой карте? Получить справку можно в мобильном приложении или Альфа-Онлайн: Счёт карты → Справки и выписки. Справку в формате PDF с подписью и синей печатью от"
score : 0.4805419542068225
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1569    заказать справку о реквизиты счета
Name: query, dtype: object "
Title of doc:
"900    Загрузить справки в систему «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Получите справку о закрытии кредитного счета в стороннем банке и загрузите ее скан или фотографию с помощью специального приложения. Если у вас еще нет логина в интернет-банке «Альфа‑Онлайн», зарегист"
score : 0.4343878427208555
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1569    заказать справку о реквизиты счета
Name: query, dtype: object "
Title of doc:
"861    Телефонный центр «Альфа-Консультант» — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Доступные операции по телефону Подключить / отключить услуги «Альфа-Мобайл», «Альфа-Клик», «Альфа-Чек», «Альфа-Диалог» Получить детальную информацию по всем счетам Открыть текущие счета, накопительные"
score : 0.4277399698472104
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1569    заказать справку о реквизиты счета
Name: query, dtype: object "
Title of doc:
"1029    Как правильно закрыть кредитную карту — грамотное и быстрое закрытие кредитки в банке | Полезные статьи от 🅰️ Альфа-Банка
Name: title, dtype: object"
Chunk from doc:
"по карте. Пополнив кредитный счёт на сумму, равную остатку задолженности, нужно удостовериться, что банк получил деньги. Проверить это можно онлайн через личный кабинет на сайте или в мобильном прилож"
score : 0.3800580455371183
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1569    заказать справку о реквизиты счета
Name: query, dtype: object "
Title of doc:
"1032    Как сделать чтобы одобрили кредитную карту – Как повысить вероятность одобрения кредитки – Блог "Альфа-Банка"
Name: title, dtype: object"
Chunk from doc:
"Кредитная карта — полезный и удобный инструмент, с помощью которого можно осуществлять безналичные расчёты в магазинах, ресторанах, пунктах обслуживания и делать покупки в интернете. Оформить её прост"
score : 0.3613858985988529
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3852    До какого числа хранение моего стикера в г. Находка?
Name: query, dtype: object "
Title of doc:
"1069    Как расплачиваться телефоном вместо карты: 🅰 оплата телефоном и бесконтактная оплата
Name: title, dtype: object"
Chunk from doc:
"карты не хранятся на серверах и в телефоне, не видны посторонним, в отличие от ситуации с применением пластика. Если гаджет украдут, вор не сможет им оплатить покупки, ведь нужно ввести пин-код или ск"
score : 0.2675747866295305
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3852    До какого числа хранение моего стикера в г. Находка?
Name: query, dtype: object "
Title of doc:
"1638    Приложение банка для самозанятых от 🅰️ Альфа‑Банка — Удобное мобильное приложение для самозанятых
Name: title, dtype: object"
Chunk from doc:
"дома Переведём самозанятость к нам Пара кликов — и вы самозанятый с Альфа‑Банком Оформите самозанятость в Альфа‑Банке Другие предложения для самозанятых Полезные инструменты Приложение Сфера деятельно"
score : 0.2526763379573822
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3852    До какого числа хранение моего стикера в г. Находка?
Name: query, dtype: object "
Title of doc:
"1658    Бивалютный депозит для ИП и малого бизнеса: тарифы от «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"следующего рабочего дня. Где можно посмотреть рыночный курс, с которым идёт сравнение при возврате депозита? На сайте Московской биржи: http://moex.com/en/fixing/. Чем определяется максимальный размер"
score : 0.2501221895217895
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3852    До какого числа хранение моего стикера в г. Находка?
Name: query, dtype: object "
Title of doc:
"113    Подтверждение номера телефона
Name: title, dtype: object"
Chunk from doc:
"Вопросы и ответы Почему я получил сообщение, что мой номер неактуален? Что делать, если другой человек указал мой номер телефона и подтвердил его? Что делать, если я не могу зайти в Альфа‑Онлайн или п"
score : 0.2501106262207031
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3852    До какого числа хранение моего стикера в г. Находка?
Name: query, dtype: object "
Title of doc:
"1906    Перевыпуск дебетовой карты
Name: title, dtype: object"
Chunk from doc:
"реквизитов пластика зависит от причины перевыпуска. Если речь идёт о плановом выпуске, номер останется тем же, изменится срок действия и CVC-код. Если замена произведена досрочно, то все данные на пла"
score : 0.245776054695599
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4632    Я инвесткопилки деньги переводить на карту, Мне смски пришел код а я ждала код не пришёл вовще, номер телефона правильно
Name: query, dtype: object "
Title of doc:
"1610    Мобильный банк Альфа-Онлайн
Name: title, dtype: object"
Chunk from doc:
"Стать клиентом Привет! Войдите в Альфа‑Онлайн Номер телефона Номер телефона Вперёд Войти по логину и паролю Быстрый вход В приложении Альфа-Банка перейдите в Профиль → Войти в интернет банк и отсканир"
score : 0.399219996545997
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4632    Я инвесткопилки деньги переводить на карту, Мне смски пришел код а я ждала код не пришёл вовще, номер телефона правильно
Name: query, dtype: object "
Title of doc:
"1554    Что такое перевод СБП?
Name: title, dtype: object"
Chunk from doc:

In [35]:
print(data[data.web_id == 579]['title'])

578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object

In [14]:
questions

      q_id                                              query
0        1                                        Номер счета
1        2                              Где узнать бик и счёт
2        3  Мне не приходят коды для подтверждения данной ...
3        4  Оформила рассрочку ,но уведомлений никаких не ...
4        5  Здравствуйте, когда смогу пользоваться кредитн...
...    ...                                                ...
6972  6973  Здравствуйте, оплатил вчера ЖКХ а кэшбек не на...
6973  6974  Здравствуйте,  можно ли заказать реквизиты бан...
6974  6975  Здравствуйте, подскажите пожалуйста где я могу...
6975  6976                  Реквизиты для оплаты номера карты
6976  6977  Можно ли отключить автопополнение брокерского ...

[6977 rows x 2 columns]